### PR TITLE
Updated to 1.9.3.6 from OpenMage/magento-mirror

### PR DESCRIPTION
**Pull request by OriPekelman**
We should possibly consider upstreaming the example from there .. or mechanize the updates.
I have not tested this to be running.

### CODE REVIEW

**Comment by Crell** [comment]
This is a ginormous diff, so I cannot review it.  I assume it's mainly just "update code changes from upstream, make sure it still installs"?

**Comment by OriPekelman** [comment]
This is the reality of Magento. This is only an update from upstream. It should be done for every release.  And it should be tested. Assuming it works would be too bold. Otherwise, we would have an example with known vulnerabilities... which should be avoided.

**Comment by Crell** [comment]
Seems to work as well as the current master branch in my testing.  I don't know how to fully test out Magento, but spot testing seems to be the same.  Good enough to merge for me.

**Comment by Crell** [comment]
Thanks, @OriPekelman

**Pull request merged**
