### PR TITLE
Set $debug to TRUE

### PR DESCRIPTION
**Pull request by JGrubb**

### CODE REVIEW

**Comment by Crell** [comment]
Are you should we should be setting debug mode on for a real project?

**Comment by JGrubb** [comment]
It only prints out to stdout (build and deploy logs), and it’s extremely helpful when setting this up initially to have that be on.  I think debug = true as a default is helpful.

**Comment by Crell** [comment]
Let's include a comment about it, then, as otherwise I can see other people going "debug true in production? What are you folks smoking?"

**Comment by JGrubb** [comment]
Haha, yes. It's super easy to miss that most useful setting, that's why I feel like it should be the starting point, but I get your point.

Feel free to alter that comment as you see fit if you think it needs work.

**Pull request merged**
